### ISSUE TITLE
Multi OP.GG update in #bonesy-control

### ISSUE THREAD

**Issue by anrkparker** [anrkparker/bonesy#9]
1. Clarify the function of the multi menu in #bonesy-control. 
2. Add captain names to the multi menu

Edit embed
{Title:} **React here to receive a multi op.gg**
{FieldTitle:} :cherry_blossom: Pink - :Gold: {custom emoji}
{FieldDescription:} Cpt: @thefrogmigration**

(repeat process for each team)

**Comment by Bobbyt1500** [comment]
Completed
